name: default
on: workflow_dispatch
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
     - name: setup
       run: curl -sSL https://install.python-poetry.org | python3 -
     - name: gene
       run: poetry run genfilter -t all
