name: default
on: workflow_dispatch
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3.3.0
     - name: setup
       run: curl -sSL https://install.python-poetry.org | python3 -
     - name: gene
       run: |
         poetry install
         poetry run genfilter -t all
