name: main
on:
  schedule:
   - cron:  '30 5,17 * * *'
  workflow_dispatch:
jobs:
  gen_filter:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v6
     - uses: actions/setup-python@v6
       with:
         python-version: '3.14' 
     - name: Install jq
       uses: dcarbone/install-jq-action@v3
     - name: install uv
       uses: astral-sh/setup-uv@v8.2.0
     - name: get release tag
       run: |
         export release_tag=$(curl https://api.github.com/repos/v2fly/domain-list-community/releases/latest | jq -r '.tag_name')
         echo "release_tag=$release_tag" >> $GITHUB_ENV
     - name: generate
       run: |
         uv sync
         uv run genfilter -t all -g $release_tag
     - name: Commit & Push changes
       uses: EndBug/add-and-commit@v10
       with:
         message: ${{ env.release_tag }}
